### ISSUE TITLE
filtering actions

### ISSUE THREAD

**Issue by albertodiaz** [deerawan/yii2-advanced-api#2]
Hi, first, thanks for sharing.

I would like to ask you if it is possible to use the filter of actions in the urlManager by using 'only' and 'except' such as the documentation.

https://github.com/yiisoft/yii2/blob/master/docs/guide/rest-routing.md

Example:

        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => true,
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => 'v1/country',
                    'only' => ['get'],
                    'tokens' => [
                        '{id}' => '<id:\\w+>'
                    ]

                ]
            ],
        ]

Thanks

**Comment by deerawan** [comment]
Hi @albertodiaz, I think it is possible. I have not tried it though. Probaby you need to update the Yii version.
