### ISSUE TITLE
[bug-report]  yii2-advanced-api/api/config/main.php line 16

### ISSUE THREAD

**Issue by zuoRambo** [deerawan/yii2-advanced-api#4]
there have some questions in the blow code:
```
'basePath' => '@app/modules/v1',
```
i think it should be 
```
'basePath' => '@api/modules/v1’,
```

**Comment by mehrna** [comment]
@zuoRambo No, its completely true!
refer to Yii2 documents:
[Predefined Aliases](http://www.yiiframework.com/doc-2.0/guide-concept-aliases.html#predefined-aliases)
and as [Kartik V](http://www.yiiframework.com/user/79399/) lists path aliases [here](http://www.yiiframework.com/wiki/667/yii-2-list-of-path-aliases-available-with-default-basic-and-advanced-app/), `@app` is current application's (frontend/backend/console/api) root directory in advanced template.

**Comment by deerawan** [comment]
@mehrna agree with you! 👍
