### ISSUE TITLE
Licence and code ownership quesiton

### ISSUE THREAD

**Issue by tomaszbrunarski** [deerawan/yii2-advanced-api#6]
Hi, I wanted to ask about the ownership of the code. Why is there mentioning of company called Ebizu in the code? do they have ownership of this code ? Also I see only yii app advanced standard licence and nothing else, so am I to believe that you have full ownership and the code, and no one can use this code as per http://stackoverflow.com/questions/1190628/what-license-is-public-code-under-if-no-license-is-specified ?

**Comment by deerawan** [comment]
Hi @tomaszbrunarski, ah yes I didn't notice that copyright with my company name was there. I will remove it and push it back to master. This is code is available for public though. Feel free to modify and make experiment on it.

**Comment by tomaszbrunarski** [comment]
Thank you for a quick reply, the problematic part is that your software doesnt contain its own licence, meaninng any soft derived from this is in fact copyrighted by you and cannot be changed, I can see only a licence of yii2 framework which is something connected only to yii2 framework. Can you also update the licence?

Also how did that Ebizu name got there in the first place, did you speak with them and let them know that their software will be used for open source project? Are they ok with it? I am reviewing the code for a client and dont want to have a lawsuit on his hands after he deploys.

**Comment by deerawan** [comment]
@tomaszbrunarski Basically, the source code is modified version based on Yii2 app advanced https://github.com/yiisoft/yii2-app-advanced. I just added api configuration on it. So, I didn't have thought to create its own license. 

I have checked files with ebizu name on it, it was almost mentioned on *tests* files which I created for a project using this repo source code. I think I accidentally copied the tests into this. I just realized when you told me about this. I'm really sorry to make you worry and confused. 

I'm working to remove all test files. Literally, those files are not needed here. Will push it back to master ASAP.

if you can't wait for me and want to use this repo, I can guarantee you it is safe and permission allowed. You can just remove all files with ebizu name on it. 

Thank you.
